tabWidth: 4
singleQuote: true
semi: true
vueIndentScriptAndStyle: true
trailingComma: all
jsxSingleQuote: false
endOfLine: auto
printWidth: 160
overrides:
  - files: ['*.vue']
    options:
      printWidth: 120
  - files: ['*.yml', '*.yaml']
    options:
      tabWidth: 2
