/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  discord: {
    test: boolean;
    token: string;
    serverID: string;
    commandChannelID: string;
    voiceChannelID: string;
    ignoredUsers?: string[];
  };
  scorePlayers: {
    displayName: string;
    pronouns: string;
    twitch: string;
    country: string;
    discord: string;
    discordProfileUrl: string;
  }[];
  [k: string]: unknown;
}
