/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExternalBingoboardMeta =
  | {
      game: "ori1";
      boardID: string;
      playerID: string;
      coop: boolean;
      [k: string]: unknown;
    }
  | {
      game: "ori2";
      /**
       * The sync token, obtained through the Rando launcher or web interface
       */
      token: string;
      /**
       * The Rando server host
       */
      host?: string;
      [k: string]: unknown;
    }
  | {
      game: "deus-ex";
      [k: string]: unknown;
    }
  | {
      game: "none";
      [k: string]: unknown;
    };
