/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ObsStreamsInternal {
  layout: string;
  streams: {
    channel: string;
    x: number;
    y: number;
    width: number;
    height: number;
    originalWidth: number;
    originalHeight: number;
    cropTop: number;
    cropBottom: number;
    cropLeft: number;
    cropRight: number;
    quality: string;
    volume: number;
    muted: boolean;
    paused: boolean;
    visible: boolean;
    streamUrl: string;
    availableQualities: {
      name: string;
      width: number;
      height: number;
      streamUrl: string;
      masterUrl: string;
    }[];
  }[];
}
