/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OriBingoMeta {
  active: boolean;
  game: "ori1" | "ori2";
  boardID: number;
  playerID: string;
  coop: boolean;
}
