name: CI
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
    
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
        
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Run ESLint
        run: npm run build
