name: CI
on:
  - push
  - pull_request

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install modules
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build
        
